name: Homes By Houze
favicon: null
layout_spectrum: 0.6471157218329608
typography_spectrum: 0.508614897960797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.34343413705937564
  lightness: 0.1749950668308884
  saturation: 0.12439399701543152
  rhythmicContrast: 0.7935028867796063
purpose: []
